language: scala
scala: 2.12.7
os: linux
jdk: oraclejdk8
script:
  - scripts/travis.sh
matrix:
  include:
    - env: SBT_COURSIER=1
    - env: SBT_SHADING=1
    - env: SBT_PGP_COURSIER=1
branches:
  only:
  - master
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt
  - $HOME/.cache
