dist: xenial
group: stable

language: scala
jdk: openjdk11

before_script:
 - export JVM_OPTS="-Dfile.encoding=UTF-8 -Xmx1G -Xms1G -server -XX:ReservedCodeCacheSize=128M"
 - unset _JAVA_OPTIONS

addons:
  apt:
    packages:
      - clang
      - libunwind-dev

script: sbt scripted

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -delete
  - find $HOME/.sbt        -name "*.lock"               -delete
