dist: xenial
group: stable
sudo: required

language: scala
matrix:
  include:
    - jdk: openjdk8
      before_install:
        - PATH=$(echo "$PATH" | sed -e 's/:\/usr\/local\/lib\/jvm\/openjdk11\/bin//')
        - JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-amd64
      apt:
        packages:
          - openjdk8
    - jdk: openjdk11

before_install:
  - bash scripts/travis_setup.sh

before_script:
 - export JVM_OPTS="-Dfile.encoding=UTF-8 -Xmx1G -Xms1G -server -XX:ReservedCodeCacheSize=128M"
 - unset _JAVA_OPTIONS

script: sbt scripted

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt

before_cache:
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -delete
  - find $HOME/.sbt        -name "*.lock"               -delete
