language: java
os: linux
jdk: openjdk8
git:
  depth: false # https://stackoverflow.com/a/51727114/3714539
before_install:
  - mkdir .bin
  - curl -Lo .bin/sbt https://github.com/coursier/sbt-extras/raw/5fb3c11d689d5aad1ead8c2ecf02e1177e5d6a88/sbt
  - chmod +x .bin/sbt
  - export PATH="$(pwd)/.bin:$PATH"
  - export TRAVIS_SCALA_VERSION=2.12.8
script: scripts/travis.sh
stages:
  - name: test
  - name: release
    if: (branch = master AND type = push) OR (tag IS present)
jobs:
  include:
    - env: SBT_COURSIER=1 TEST_GROUP=1
    - env: SBT_COURSIER=1 TEST_GROUP=2
    - env: SBT_SHADING=1
    - env: SBT_PGP_COURSIER=1
    - env: LM_COURSIER=1 TEST_GROUP=1
    - env: LM_COURSIER=1 TEST_GROUP=2
    - stage: release
      script: sbt ci-release
branches:
  only:
  - master
  - /^v\d+\.\d+.*$/ # tagged versions
cache:
  directories:
  - $HOME/.ivy2/cache
  - $HOME/.sbt
  - $HOME/.cache
